### ISSUE TITLE
Previous 2 weeks tab

### ISSUE THREAD

**Issue by Rohithgilla12** [covindia/CovIndia-Website#59]
Create a new tab where we will show the India map with only cases in the last 2 weeks. The end-point can be found here: https://v1.api.covindia.com/past-two-weeks. The map will be exactly like our current map (which is cumulative from the beginning) but will show data for only last 2 weeks.  This tab will appear as a button near the play button currently. Please note the legend will also be different. The ticks for the legend can be found in the key split points.

**Comment by ach4l** [comment]
I think if we move to the new sheet, we will not have the last two weeks tab any more. So you can close this issue.
