### ISSUE TITLE
Color contrast issues 

### ISSUE THREAD

**Issue by bhansa** [covindia/CovIndia-Website#73]
![image](https://user-images.githubusercontent.com/9723884/80856102-a3be5700-8c64-11ea-83eb-8edabe75e5bd.png)

On zones.html the text contrast is less, compare to the background color.
It might not be visible on few devices as well, like big monitors with high contrast. We need to increase the contrast ratio for text available on the page to make it more visibly accessible.

**Comment by Rohithgilla12** [comment]
Yeah thanks, true.
What change of color would make it accessible?

**Comment by bhansa** [comment]
I have tested using [WAVE tool](https://wave.webaim.org/). I suggest below background colors for different zones:
Red Zone: ![#C20000](https://placehold.it/15/C20000/000000?text=+) `#C20000` Contrast: 6.37:1
Orange Zone: ![#98621B](https://placehold.it/15/98621B/000000?text=+) `#98621B` Contrast: 5.12:1
Green Zone: ![#006600](https://placehold.it/15/006600/000000?text=+) `#006600` Contrast: 7.24:1

**Comment by qurram-zaheer** [comment]
Thanks! Changed the colors and now closing the issue
