### ISSUE TITLE
IP Address Look-Up

### ISSUE THREAD

**Issue by IceCereal** [covindia/CovIndia-Website#78]
There was an attempt to get the client's IP Address to automatically show their district when they open the site by making an end-point in Covindia-BigDataBox (tagging @covindia/backend). In particular, [This PR](https://github.com/covindia/CovIndia-BigDataBox/pull/10) was closed because of the reasons explained there.

What is needed is for the website to look up the location automatically via the client's IP Address and getting their city and opening a tooltip associated with that city in using the function `renderData` that can be found in `index.html`.

http://api.db-ip.com/v2/free/ENTER-IP-ADDRESS-HERE can be used

**Comment by ruralad** [comment]
IP address cant be reliable for locating a persons exact location. 
For example, there is more than **200km** difference from my actual location and the one my ipv4 is pointing to.
"IPv4 information should not be used for emergency purposes, trying to find someone's exact physical address, or other purposes that would require 100% accuracy." - whatismyipaddress.com

**Comment by IceCereal** [comment]
Oh yes, you're 100% right. Your public IP address is (for the majority of people) the location of their ISP / regional ISP. However, for many people, their ISP is located in the same city as them and that was our reasoning behind going ahead with this. Currently, the website shows a few cities by default and we thought of adding the city / district where the client stays as an automatic tool-tip. If it turns out to be the same district, it's a plus point. If it doesn't, it just appears as another default tool-tip for the client.
